Convert e2e to workflow_dispatch
* Fixed checkout of branch after merge in e2e

Signed-off-by: kouki <kouworld0123@gmail.com>

diff --git a/.github/workflows/ci-e2e.yaml b/.github/workflows/ci-e2e.yaml
--- a/.github/workflows/ci-e2e.yaml
+++ b/.github/workflows/ci-e2e.yaml
@@ -7,11 +7,7 @@ on:
     paths-ignore:
       - '**.md'
       - "containers/**"
-  pull_request:
-    types: [opened, synchronize]
-    paths-ignore:
-      - '**.md'
-      - "containers/**"
+  workflow_dispatch:
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -26,17 +22,48 @@ env:
 #
 # NOTE: Current Cybozu internal use version is 8.0.28.
 jobs:
+  commit-status-start:
+    name: Commit status start
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Set pending to commit status
+        uses: myrotvorets/set-commit-status-action@38f3f27c7d52fb381273e95542f07f0fba301307 # v2.0.0
+        with:
+          sha: ${{ github.sha }}
+  extract-github-ref:
+    name: extract github.ref
+    runs-on: ubuntu-22.04
+    outputs:
+      github_ref: ${{ steps.extract.outputs.github_ref }}
+    steps:
+      - uses: actions/checkout@v4
+      - name: Extract github.ref
+        id: extract
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          # if exists PR refs/pull/<pull_request_number>/merge
+          # if not exists PR → github.ref
+          PR_number=$(gh pr view --json number -q .number)
+          if [ $? == 0 ];then
+            echo "github_ref=refs/pull/${PR_number}/merge" >> $GITHUB_OUTPUT
+          else
+            echo "github_ref=${{ github.ref }}" >> $GITHUB_OUTPUT
+          fi
   dbtest:
     name: Integration tests with MySQL
+    needs: extract-github-ref
     strategy:
       matrix:
         mysql-version: ["8.0.28", "8.0.34", "8.0.35"]
     uses: ./.github/workflows/dbtest.yaml
     with:
       mysql-version: ${{ matrix.mysql-version }}
+      ref: ${{ needs.extract-github-ref.outputs.github_ref }}
 
   e2e:
     name: Supported Kubernetes versions End-to-End Tests
+    needs: extract-github-ref
     strategy:
       matrix:
         mysql-version: ["8.0.35"]
@@ -45,9 +72,11 @@ jobs:
     with:
       k8s-version: ${{ matrix.k8s-version }}
       mysql-version: ${{ matrix.mysql-version }}
+      ref: ${{ needs.extract-github-ref.outputs.github_ref }}
 
   e2e-mysql:
     name: Supported MySQL versions End-to-End Tests
+    needs: extract-github-ref
     strategy:
       matrix:
         mysql-version: ["8.0.28", "8.0.34", "8.0.35"]
@@ -56,13 +85,17 @@ jobs:
     with:
       k8s-version: ${{ matrix.k8s-version }}
       mysql-version: ${{ matrix.mysql-version }}
+      ref: ${{ needs.extract-github-ref.outputs.github_ref }}
 
   upgrade:
     name: Upgrade Test
+    needs: extract-github-ref
     runs-on:
       group: moco
     steps:
       - uses: actions/checkout@v4
+        with:
+          ref: ${{ needs.extract-github-ref.outputs.github_ref }}
       - uses: actions/setup-go@v4
         with:
           go-version-file: go.mod
@@ -84,3 +117,26 @@ jobs:
         with:
           name: logs-upgrade.tar.gz
           path: e2e/logs.tar.gz
+  commit-status-final:
+    if: always()
+    name: Commit Status Final
+    needs:
+      - dbtest
+      - e2e
+      - e2e-mysql
+      - upgrade
+    runs-on: ubuntu-latest
+    steps:
+      - name: Get final status
+        id: final-status
+        run: |
+          if "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}"; then
+            echo "result=failure" >> $GITHUB_OUTPUT
+          else
+            echo "result=success" >> $GITHUB_OUTPUT
+          fi
+      - name: Set final commit status
+        uses: myrotvorets/set-commit-status-action@38f3f27c7d52fb381273e95542f07f0fba301307 # v2.0.0
+        with:
+          sha: ${{ github.sha }}
+          status: ${{ steps.final-status.outputs.result }}
